### ISSUE TITLE
Search tabs by url 

### ISSUE THREAD

**Issue by jknight** [deanishe/alfred-firefox#10]
Great plugin, thanks for creating it !

I see that tab search is limited to the window title. I often want to search tabs by URL. 

Is there any easy way to add url filtering/searching of tabs ?

**Comment by deanishe** [comment]
> Is there any easy way to add url filtering/searching of tabs ?

It's fairly straightforward to do. You just need to call [`Item.Match`](https://godoc.org/github.com/deanishe/awgo#Item.Match) [on each search result item](https://github.com/deanishe/alfred-firefox/blob/152aa0e426c5698b8e6ab6061e680ac1d96429b0/client.go#L343) to set different keywords to compare the search query to.

But I don't think adding the full URL is a good idea because you'll get a lot of shitty matches. I'd only add the domain, or *possibly* `domain.com/plus/path`.

**Comment by GJRobert** [comment]
> But I don't think adding the full URL is a good idea because you'll get a lot of shitty matches. I'd only add the domain, or _possibly_ `domain.com/plus/path`.

May I ask if this proposed enhancement has been implemented yet?
