### ISSUE TITLE
filter tabs filter not 100 % functional

### ISSUE THREAD

**Issue by petebrag** [deanishe/alfred-firefox#21]
the Filter Tabs script does not work fully.  Everything works except the browser doesn't go to the page selected.  In other words, the tab names come up, you can select, but the page does not change and go there. This works on one of my computers (macbook pro 2013) but not on a mac mini m1.  The scripts for bookmarks and history work and the results can be chosen and the page goes there but not with open tabs.

**Comment by brttbndr** [comment]
This sounds like the same issue as https://github.com/deanishe/alfred-firefox/issues/23

See my comments there for a workaround.

**Comment by petebrag** [comment]
Ok, thanks. Can you tell where I can find someone who can assist me with this because I'm not a coder at all? What language is this using, perhaps I can find someone on Fiverr or perhaps on the Alfred boards? Any help would be appreciated. thanks.

**Comment by brttbndr** [comment]
Here's an unofficial build of the universal binary. Your mileage may vary, and you should consider whether to trust the opaque blob of compiled code I'm providing.

https://github.com/brttbndr/alfred-firefox/releases/tag/universal-binary

Download and extract the `alfred-firefox.zip` file from that build.

In Alfred, right-click the workflow and select Open in Finder.

Rename the original `alfred-firefox` (so that you have a backup) in the workflow folder, and then copy in the new one you just extracted.

You can observe that the new file is about twice as large as the old one (because it has code for both Intel and Apple chips).

Restart Firefox to ensure you are running this new file and you should get filter tabs working as designed. If not, double-check that you're seeing "Apple" as the platform in Activity Monitor.

**Comment by petebrag** [comment]
great, thanks a lot. i got someone to do it and it works. :)
