### ISSUE TITLE
Firefox-esr

### ISSUE THREAD

**Issue by fguada** [deanishe/alfred-firefox#9]
Hello,
I can't run the Firefox extension in Firefox-esr, because extension require Firefox 70+ and esr is 68. Could you adapt extension to Firefox-esr?
Thanks.

**Comment by deanishe** [comment]
I picked v70 because it was the current version at the time I started writing the extension. It is also compatible with v68 as far as I can tell.

I've [uploaded a new version compatible with Firefox ESR](https://addons.mozilla.org/en-US/firefox/addon/alfred-launcher-integration/), but it hasn't been approved yet (currently, it's in position 98 in the approvals queue).

It should be available tomorrow.

**Comment by fguada** [comment]
That's fast! Thank you.

**Comment by deanishe** [comment]
> That's fast!

Well, I didn't have to change anything but a couple of version numbers…

**Comment by deanishe** [comment]
[The new version is live](https://addons.mozilla.org/en-US/firefox/addon/alfred-launcher-integration/). Can you let me know if it works?

**Comment by fguada** [comment]
It works perfectly! Thank you.
